force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The standard owner field. The sales rep assigned to this territory</description>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <description>The standard name field. Each record will be named after its specific zip code.</description>
    <label>Zip Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/verifyAccountOwners.cls
global class verifyAccountOwners implements Schedulable {
    global void execute (SchedulableContext ctx){
        List<Account> accts = [SELECT BillingPostalCode, OwnerId FROM Account];
        List<Territory__c> trrts = [SELECT Zip_Code__c, Owner__c FROM Territory__c];
        Boolean assignedToProperOwner = false;

        List<Territory__c> filteredTerritories = new List<Territory__c>();
        List<Account> accToUpdate = new List<Account>();
                
        for(Account a : accts){
            for(Territory__c t : trrts){
                if(a.BillingPostalCode == t.Zip_Code__c && a.OwnerId == t.owner__c){
                    assignedToProperOwner = true;                
                }
            }
            if(!assignedToProperOwner){
                accToUpdate.add(a);
            }
        }
        system.debug('accToUpdate ' + accToUpdate);
        if(accToUpdate !=null){
            AccountController.assignRandomOwner(accToUpdate);
        }
    }
}

            